name: suzuki
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.53

environment:
  sdk: ">=2.17.6 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  font_awesome_flutter: ^9.2.0
  http: ^0.13.4
  dio: ^4.0.4
  card_swiper: ^1.0.4
  skeleton_text: ^3.0.1
  onesignal_flutter: ^3.3.0
  permission_handler: ^8.3.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.18
  flutter_launcher_icons: ^0.9.0
  shared_preferences: ^2.0.12
  intl: ^0.18.0
  geolocator: 7.0.0
  geocoding: ^2.1.0
  google_maps_flutter: ^2.1.3
  sprintf: ^6.0.0
  random_string: ^2.3.1
  visibility_detector: ^0.2.2
  # flutter_locker: ^2.0.3
  image_picker: ^0.8.2
  flutter_svg: ^0.22.0
  # flutter_html: ^2.2.1
  flutter_super_html_viewer: ^0.1.0
  flutter_image_compress: ^1.1.0
  sqflite: ^2.0.2
  path_provider: ^2.0.11
  device_info_plus: ^4.0.0
  move_to_background: ^1.0.2
  photo_view: ^0.14.0
  camera: ^0.10.0
  flutter_slidable: ^1.3.0
  share_plus: ^4.0.10+1
  file_picker: ^5.0.1
  flutter_locker: ^2.1.0+1
  local_auth: ^2.1.0
  table_calendar: ^3.0.9
  easy_image_viewer: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^1.0.0 
  
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
